var name = ["Jaydeep","Yashu","Kumar","Srivastava"];
console.log(typeof name[3]);
var out = name.pop();
console.log("Array is:", name, "POP is: ",out);
var out = name.pop();
console.log("Array is:", name, "POP is: ",out);
var out = name.pop();
console.log("Array is:", name, "POP is: ",out);
var out = name.pop();
console.log("Array is:", name, "POP is: ",out);
var out = name.pop();
console.log("Array is:", name, "POP is: ",out);
var b=true;
console.log(b);
console.log(typeof b);